=== JuniorNatalin/Selco_Senai/1304915/C/KRC/Roboter/Config/System/Common/Schemes/KagaBaseConfig.xsd
<?xml version="1.0" encoding="UTF-8"?>
<!--W3C Schema erstellt mit Notepad++ v4.8.5 -->
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema">
   <xs:include schemaLocation="Version.xsd"/>
   <xs:element name="KagaConfig">
      <xs:complexType>
         <xs:sequence>
            <xs:element ref="Version"/>
            <xs:element ref="PriorityConfig" maxOccurs="1" minOccurs="0"/>
            <xs:element ref="Debugging" maxOccurs="1" minOccurs="0"/>
            <xs:element ref="PublicBus" maxOccurs="2" minOccurs="0"/>
            <xs:element ref="GeneralSettings" maxOccurs="1" minOccurs="0"/>
            <xs:element ref="Configuration" maxOccurs="2" minOccurs="0"/>
            <xs:element ref="BandwidthLimitSettings" maxOccurs="1" minOccurs="0"/>
            <xs:element ref="SystemNATConfigs" maxOccurs="1" minOccurs="0"/>
         </xs:sequence>
      </xs:complexType>
   </xs:element>
   <xs:element name="PublicBus">
      <xs:complexType>
         <xs:attribute name="BlockTelnet" type="xs:boolean" use="required"/>
         <xs:attribute name="BusId" type="xs:string" use="required"/>
         <xs:attribute name="NumSystemNatRules" type="xs:int" use="optional"/>
         <xs:attribute name="IcmpBlockFilter" type="xs:int" default="128" use="optional"/>
      </xs:complexType>
   </xs:element>
   <xs:element name="GeneralSettings">
      <xs:complexType>
         <xs:attribute name="SetHostname" type="xs:boolean" use="required"/>
         <xs:attribute name="AddBridgeInterface" type="xs:boolean" use="required"/>
      </xs:complexType>
   </xs:element>
   <xs:element name="Debugging">
      <xs:complexType>
         <xs:attribute name="KLIIfName" type="xs:string" use="required"/>
         <xs:attribute name="KLIIfUnit" type="xs:int" use="required"/>
         <xs:attribute name="KSBIfName" type="xs:string" use="required"/>
         <xs:attribute name="KSBIfUnit" type="xs:int" use="required"/>
         <xs:attribute name="Debugging" use="required">
            <xs:simpleType>
               <xs:restriction base="xs:string">
                  <xs:pattern value="off|KLI|KSB"/>
               </xs:restriction>
            </xs:simpleType>
         </xs:attribute>
      </xs:complexType>
   </xs:element>
	<xs:element name="PriorityConfig">
		<xs:complexType>
			<xs:attribute name="NetTaskPriority" type="xs:int" use="required"/>
			<xs:attribute name="ipdhcpcPriority" type="xs:int" use="required"/>
			<xs:attribute name="ipdhcpsPriority" type="xs:int" use="optional"/>
			<xs:attribute name="ipcom_syslogdPriority" type="xs:int" use="required"/>
			<xs:attribute name="ipcom_telnetdPriority" type="xs:int" use="required"/>
			<xs:attribute name="lwIPPriority" type="xs:int" use="required"/>
		</xs:complexType>
	</xs:element>
	<xs:element name="Configuration">
		<xs:complexType>
			<xs:sequence>
				<xs:element ref="Bus" maxOccurs="5" minOccurs="0"/>
			</xs:sequence>
		    <xs:attribute name="Type" use="required">
				<xs:simpleType>
					<xs:restriction base="xs:string">
					<xs:pattern value="Standard|RoboTeam"/>
				</xs:restriction>
				</xs:simpleType>
			</xs:attribute>
		</xs:complexType>
	</xs:element>
	<xs:element name="Bus">
      <xs:complexType>
         <xs:attribute name="ConfigFile" type="xs:string" use="required"/>
         <xs:attribute name="Id" type="xs:string" use="required"/>
         <xs:attribute name="NetworkInterface" type="xs:string" use="required"/>
         <xs:attribute name="Path" type="xs:string" use="required"/>
         <xs:attribute name="isBroadcastDetectionActive" type="xs:boolean" use="optional"/>
         <xs:attribute name="PacketLimit" type="xs:int" use="optional"/>
         <xs:attribute name="BandwidthLimit" type="xs:int" use="optional"/>
         <xs:attribute name="Mainboard" type="xs:string" use="optional"/>
      </xs:complexType>
   </xs:element>
   <xs:element name="BandwidthLimitSettings">
      <xs:complexType>
         <xs:sequence>
            <xs:element ref="BandwidthLimit" maxOccurs="3" minOccurs="0"/>
         </xs:sequence>
      </xs:complexType>
   </xs:element>
   <xs:element name="BandwidthLimit">
      <xs:complexType>
         <xs:attribute name="Id" type="xs:string" use="required"/>
         <xs:attribute name="Timeout" type="xs:int" use="required"/>
         <xs:attribute name="Bandwidth" type="xs:int" use="required"/>
         <xs:attribute name="Limit" type="xs:int" use="required"/>
      </xs:complexType>
   </xs:element>
   <xs:element name="SystemNATConfigs">
      <xs:complexType>
         <xs:sequence>
            <xs:element ref="SystemNAT" maxOccurs="3" minOccurs="0"/>
         </xs:sequence>
      </xs:complexType>
   </xs:element>
   <xs:element name="SystemNAT">
      <xs:complexType>
         <xs:sequence>
            <xs:element name="NATRule" type="xs:string" maxOccurs="10" minOccurs="0"/>
         </xs:sequence>
         <xs:attribute name="BusId" type="xs:string" use="required"/>
      </xs:complexType>
   </xs:element>
</xs:schema>

=== JuniorNatalin/Selco_Senai/1304915/C/KRC/Roboter/Config/System/Office/KagaConfig.xml
<?xml version="1.0" encoding="UTF-8"?>
<KagaConfig xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="/Roboter/Config/System/Common/Schemes/KagaBaseConfig.xsd">
   <Version Label="">
      <Info Version="KUKA V8.3"/>
      <Schema Version="1"/>
   </Version>
   <PriorityConfig NetTaskPriority="181" ipdhcpcPriority="241" ipdhcpsPriority="250" ipcom_syslogdPriority="241" ipcom_telnetdPriority="241" lwIPPriority="131"/>
   <Debugging Debugging="off" KLIIfName="virtual" KLIIfUnit="5" KSBIfName="mirror" KSBIfUnit="0"/>
   <PublicBus BlockTelnet="false" BusId="NETWORK_CONFIG_KUKA_LINE_INTERFACE" NumSystemNatRules="3" IcmpBlockFilter="128"/>
   <PublicBus BlockTelnet="false" BusId="NETWORK_CONFIG_KUKA_OPTION_NETWORK_INTERFACE" NumSystemNatRules="3" IcmpBlockFilter="128"/>
   <GeneralSettings SetHostname="true" AddBridgeInterface="false"/>
   <Configuration Type="Standard">
      <Bus ConfigFile="KEIConfig.xml" Id="NETWORK_CONFIG_EXTENSION_INTERFACE" NetworkInterface="KUKA_NETIF_4" Path="XML_SYSCOMMON" Mainboard="KUKA SYBperf"/>
      <Bus ConfigFile="KSBConfig.xml" Id="NETWORK_CONFIG_SYSTEMBUS" NetworkInterface="KUKA_NETIF_2" Path="XML_SYSCOMMON"/>
      <Bus ConfigFile="KONIConfig.xml" Id="NETWORK_CONFIG_KUKA_OPTION_NETWORK_INTERFACE" NetworkInterface="KUKA_NETIF_3" Path="XML_USERCOMMON"/>
      <Bus ConfigFile="KLIConfig.xml" Id="NETWORK_CONFIG_KUKA_LINE_INTERFACE" NetworkInterface="KUKA_NETIF_1" Path="XML_USERCOMMON" isBroadcastDetectionActive="true" PacketLimit="20000" BandwidthLimit="6553600"/>
   </Configuration>
   <Configuration Type="RoboTeam">
      <Bus ConfigFile="KEIConfig.xml" Id="NETWORK_CONFIG_EXTENSION_INTERFACE" NetworkInterface="KUKA_NETIF_4" Path="XML_SYSCOMMON" Mainboard="KUKA SYBperf"/>
      <Bus ConfigFile="KSBConfig_VLAN.xml" Id="NETWORK_CONFIG_SYSTEMBUS" NetworkInterface="KUKA_NETIF_2" Path="XML_SYSCOMMON"/>
      <Bus ConfigFile="KONIConfig.xml" Id="NETWORK_CONFIG_KUKA_OPTION_NETWORK_INTERFACE" NetworkInterface="KUKA_NETIF_3" Path="XML_USERCOMMON"/>
      <Bus ConfigFile="KLIConfig.xml" Id="NETWORK_CONFIG_KUKA_LINE_INTERFACE" NetworkInterface="KUKA_NETIF_1" Path="XML_USERCOMMON" isBroadcastDetectionActive="true" PacketLimit="20000" BandwidthLimit="6553600"/>
   </Configuration>
   <BandwidthLimitSettings>
      <BandwidthLimit Id="BANDWIDTH_VERY_LOW" Timeout="1" Bandwidth="10" Limit="1500"/>
      <BandwidthLimit Id="BANDWIDTH_LOW" Timeout="1" Bandwidth="25" Limit="3000"/>
      <BandwidthLimit Id="BANDWIDTH_MEDIUM" Timeout="1" Bandwidth="35" Limit="4500"/>
   </BandwidthLimitSettings>
   <SystemNATConfigs>
      <SystemNAT BusId="NETWORK_CONFIG_KUKA_LINE_INTERFACE">
         <NATRule>map [GlobalNatInterface] [host:WINDOWS] -&gt; 0/32 portmap tcp/udp 18000:18999</NATRule>
         <NATRule>map [GlobalNatInterface] [host:WINDOWS] -&gt; 0/32 icmpidmap icmp 19000:19999</NATRule>
         <NATRule>rdr [GlobalNatInterface] [addr] port 3389 -&gt; [host:WINDOWS] port 3389 tcp proxy RemoteIP</NATRule>
         <NATRule>rdr [GlobalNatInterface] [addr] port 54250 -&gt; [host:WINDOWS] port 54250 tcp proxy RemoteIP</NATRule>
      </SystemNAT>
      <SystemNAT BusId="NETWORK_CONFIG_KUKA_OPTION_NETWORK_INTERFACE">
         <NATRule>map [GlobalNatInterface] [host:WINDOWS] -&gt; 0/32 portmap tcp/udp 18000:18999</NATRule>
         <NATRule>map [GlobalNatInterface] [host:WINDOWS] -&gt; 0/32 icmpidmap icmp 19000:19999</NATRule>
         <NATRule>rdr [GlobalNatInterface] [addr] port 3389 -&gt; [host:WINDOWS] port 3389 tcp proxy RemoteIP</NATRule>
         <NATRule>rdr [GlobalNatInterface] [addr] port 54250 -&gt; [host:WINDOWS] port 54250 tcp proxy RemoteIP</NATRule>
      </SystemNAT>
   </SystemNATConfigs>
</KagaConfig>
