=== JuniorNatalin/Selco_Senai/1304915/C/KRC/Roboter/Config/System/Common/Schemes/KRC.xsd
<?xml version="1.0" encoding="UTF-8"?>
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema">
   <xs:include schemaLocation="Version.xsd"/>
   <!-- todo <xs:redefine schemaLocation="Version.xsd">-->
   <!-- *************************************************
         min- and maxInclusive have to be the same value
         this value has to be changed on every change of this file !!
         *************************************************** -->
   <!--<xs:simpleType name="VersionType">
         <xs:restriction base="VersionType">
            <xs:minInclusive value="5"/>
            <xs:maxInclusive value="5"/>
         </xs:restriction>
      </xs:simpleType>
   </xs:redefine>-->
   <xs:include schemaLocation="Units.xsd"/>
   <xs:element name="KRCThread">
      <xs:complexType>
         <xs:attribute name="Priority" type="xs:integer" use="required"/>
         <xs:attribute name="CycleTime" type="xs:double" use="required"/>
         <xs:attribute name="DelayTime" type="xs:double" use="optional"/>
      </xs:complexType>
   </xs:element>
   <xs:element name="DrivesOn">
      <xs:complexType>
         <xs:attribute name="Timeout" type="usTimeType" use="required"/>
      </xs:complexType>
   </xs:element>
   <xs:element name="PowerOff">
      <xs:complexType>
         <xs:attribute name="DelayTime" type="usTimeType" use="required"/>
      </xs:complexType>
   </xs:element>
   <xs:element name="EmergencyStop">
      <xs:complexType>
         <xs:attribute name="Timeout" type="usTimeType" use="required"/>
      </xs:complexType>
   </xs:element>
   <xs:element name="Layer">
      <xs:complexType>
         <xs:attribute name="CycleTime" type="xs:integer" use="required"/>
         <xs:attribute name="ID" type="xs:integer" use="required"/>
         <xs:attribute name="PriorityOffset" type="xs:integer" use="required"/>
      </xs:complexType>
   </xs:element>
   <xs:element name="Timing">
      <xs:complexType>
         <xs:attribute name="RobotIntQuota" type="xs:double" use="required"/>
         <xs:attribute name="SubmitIntQuota" type="xs:double" use="required"/>
         <xs:attribute name="ExtSubmitInt1Quota" type="xs:double" use="optional"/>
         <xs:attribute name="ExtSubmitInt2Quota" type="xs:double" use="optional"/>
         <xs:attribute name="ExtSubmitInt3Quota" type="xs:double" use="optional"/>
         <xs:attribute name="ExtSubmitInt4Quota" type="xs:double" use="optional"/>
         <xs:attribute name="ExtSubmitInt5Quota" type="xs:double" use="optional"/>
         <xs:attribute name="ExtSubmitInt6Quota" type="xs:double" use="optional"/>
         <xs:attribute name="ExtSubmitInt7Quota" type="xs:double" use="optional"/>
         <xs:attribute name="ExprIntQuota" type="xs:double" use="required"/>
         <xs:attribute name="RobotIntDelay" type="xs:integer" use="required"/>
         <xs:attribute name="SubmitIntDelay" type="xs:integer" use="required"/>
         <xs:attribute name="ExtSubmitInt1Delay" type="xs:integer" use="optional"/>
         <xs:attribute name="ExtSubmitInt2Delay" type="xs:integer" use="optional"/>
         <xs:attribute name="ExtSubmitInt3Delay" type="xs:integer" use="optional"/>
         <xs:attribute name="ExtSubmitInt4Delay" type="xs:integer" use="optional"/>
         <xs:attribute name="ExtSubmitInt5Delay" type="xs:integer" use="optional"/>
         <xs:attribute name="ExtSubmitInt6Delay" type="xs:integer" use="optional"/>
         <xs:attribute name="ExtSubmitInt7Delay" type="xs:integer" use="optional"/>
         <xs:attribute name="ExprIntDelay" type="xs:integer" use="required"/>
      </xs:complexType>
   </xs:element>
   <xs:element name="Scheduling">
      <xs:complexType>
         <xs:sequence>
            <xs:element ref="Layer" minOccurs="10" maxOccurs="10"/>
            <xs:element ref="Timing"/>
         </xs:sequence>
         <xs:attribute name="ClockCycleTime" type="xs:double" use="required"/>
      </xs:complexType>
   </xs:element>
   <xs:element name="PcFanCheck">
      <xs:complexType>
         <xs:attribute name="AlarmRevolution" type="xs:integer" use="required"/>
         <xs:attribute name="Enable" type="xs:boolean" use="required"/>
         <xs:attribute name="ImpulsesPerRevolution" type="xs:integer" use="required"/>
         <xs:attribute name="WarningRevolution" type="xs:integer" use="required"/>
      </xs:complexType>
   </xs:element>
   <xs:element name="CabinetFanCheck">
      <xs:complexType>
         <xs:attribute name="AlarmRevolution" type="xs:integer" use="required"/>
         <xs:attribute name="Enable" type="xs:boolean" use="required"/>
         <xs:attribute name="ImpulsesPerRevolution" type="xs:integer" use="required"/>
         <xs:attribute name="WarningRevolution" type="xs:integer" use="required"/>
      </xs:complexType>
   </xs:element>
   <xs:element name="InfoHandlerThread">
      <xs:complexType>
         <xs:attribute name="CycleTime" type="usTimeType" use="required"/>
         <xs:attribute name="PowerOffDelayTime" type="usTimeType" use="required"/>
      </xs:complexType>
   </xs:element>
   <xs:element name="FctCallChannel">
      <xs:complexType>
         <xs:attribute name="Enable" type="xs:boolean" default="false"/>
         <xs:attribute name="TaskStackBytes" type="xs:unsignedInt" default="40960"/>
      </xs:complexType>
   </xs:element>
   <xs:element name="MultiSubmit">
      <xs:complexType>
         <xs:attribute name="Enable" type="xs:boolean" use="required"/>
      </xs:complexType>
   </xs:element>
   <xs:element name="AllowDoubleDollarVar">
      <xs:complexType>
         <xs:attribute name="Enable" type="xs:boolean" use="optional"/>
      </xs:complexType>
   </xs:element>
   <xs:element name="Axes">
      <xs:complexType>
         <xs:attribute name="ConfigFile" type="xs:anyURI" use="required"/>
      </xs:complexType>
   </xs:element>
   <xs:element name="WORKSPACE_PORT">
      <xs:complexType>
         <xs:attribute name="Value" type="xs:unsignedInt" use="required"/>
      </xs:complexType>
   </xs:element>
   <xs:element name="PROGSYNC_PORT">
      <xs:complexType>
         <xs:attribute name="Value" type="xs:unsignedInt" use="required"/>
      </xs:complexType>
   </xs:element>
   <xs:element name="MOTIONSYNC_PORT">
      <xs:complexType>
         <xs:attribute name="Value" type="xs:unsignedInt" use="required"/>
      </xs:complexType>
   </xs:element>
   <xs:element name="COLLAVOID_PORT">
      <xs:complexType>
         <xs:attribute name="Value" type="xs:unsignedInt" use="required"/>
      </xs:complexType>
   </xs:element>
   <xs:element name="ADS_DATENPORT">
      <xs:complexType>
         <xs:attribute name="Value" type="xs:unsignedInt" use="required"/>
      </xs:complexType>
   </xs:element>
   <xs:element name="ADS_TCP_IP">
      <xs:complexType>
         <xs:sequence>
            <xs:element ref="ADS_DATENPORT"/>
         </xs:sequence>
      </xs:complexType>
   </xs:element>
   <xs:element name="CRPORTS">
      <xs:complexType>
         <xs:sequence>
            <xs:element ref="MOTIONSYNC_PORT"/>
            <xs:element ref="WORKSPACE_PORT"/>
            <xs:element ref="PROGSYNC_PORT"/>
            <xs:element ref="COLLAVOID_PORT"/>
         </xs:sequence>
      </xs:complexType>
   </xs:element>
   <xs:element name="ApplicationOverride">
      <xs:complexType>
         <xs:attribute name="Minimum" use="required">
            <xs:simpleType>
               <xs:restriction base="xs:double">
                  <xs:minInclusive value="0.0"/>
               </xs:restriction>
            </xs:simpleType>
         </xs:attribute>
         <xs:attribute name="Maximum" use="required">
            <xs:simpleType>
               <xs:restriction base="xs:double">
                  <xs:maxInclusive value="130.0"/>
               </xs:restriction>
            </xs:simpleType>
         </xs:attribute>
      </xs:complexType>
   </xs:element>
   <xs:element name="KRC">
      <xs:complexType>
         <xs:sequence>
            <xs:element ref="Version"/>
            <xs:element ref="KRCThread"/>
            <xs:element ref="DrivesOn"/>
            <xs:element ref="PowerOff"/>
            <xs:element ref="EmergencyStop"/>
            <xs:element ref="Scheduling"/>
            <xs:element ref="MultiSubmit" minOccurs="0"/>
            <xs:element ref="AllowDoubleDollarVar"/>
            <xs:element ref="Axes"/>
            <xs:element ref="PcFanCheck" minOccurs="0"/>
            <xs:element ref="CabinetFanCheck" minOccurs="0"/>
            <xs:element ref="InfoHandlerThread"/>
            <xs:element ref="FctCallChannel" minOccurs="0"/>
            <xs:element ref="ADS_TCP_IP" minOccurs="0"/>
            <xs:element ref="CRPORTS" minOccurs="0"/>
            <xs:element ref="ApplicationOverride" minOccurs="0"/>
         </xs:sequence>
      </xs:complexType>
   </xs:element>
</xs:schema>

=== JuniorNatalin/Selco_Senai/1304915/C/KRC/Roboter/Config/System/Common/KRC.xml
<?xml version="1.0" encoding="UTF-8"?>
<KRC  xsi:noNamespaceSchemaLocation="../../System/Common/Schemes/KRC.xsd"
      xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance">
   <Version Label="">
      <Info Version="KUKA V8.3"/>
      <Schema Version="4"/>
   </Version>   

   <!-- Main thread tKRC: Should run before thread tLRS_HP-Task in layer 1 (see Scheduling element) -->
   <KRCThread
      Priority="120"
      CycleTime="4000"/>

   <DrivesOn
      Timeout="5000000"/>
   <PowerOff
      DelayTime="3000000"/>
   <EmergencyStop
      Timeout="2200000"/>

   <Scheduling ClockCycleTime="1000">
      <Layer ID="0" CycleTime= "1000" PriorityOffset="80"/>    <!-- Layer 0 -->
      <Layer ID="1" CycleTime= "4000" PriorityOffset="120"/>   <!-- Layer 1 -->
      <Layer ID="2" CycleTime="12000" PriorityOffset="160"/>   <!-- Layer 2 -->
      <Layer ID="3" CycleTime="12000" PriorityOffset="161"/>   <!-- Layer 3 (only used by ZYK_SOFT with offset 9!) -->
      <Layer ID="4" CycleTime="12000" PriorityOffset="170"/>   <!-- Layer 4 -->
      <Layer ID="5" CycleTime="12000" PriorityOffset="180"/>   <!-- Layer 5 -->
      <Layer ID="6" CycleTime="12000" PriorityOffset="190"/>   <!-- Layer 6 -->
      <Layer ID="7" CycleTime="12000" PriorityOffset="200"/>   <!-- Layer 7 -->
      <Layer ID="8" CycleTime="12000" PriorityOffset="210"/>   <!-- Layer 8 -->
      <Layer ID="9" CycleTime="12000" PriorityOffset="220"/>   <!-- Layer 9 -->
      <Timing RobotIntQuota      = "30"
              SubmitIntQuota     = "4"
              ExtSubmitInt1Quota = "1"
              ExtSubmitInt2Quota = "1"
              ExtSubmitInt3Quota = "1"
              ExtSubmitInt4Quota = "1"
              ExtSubmitInt5Quota = "1"
              ExtSubmitInt6Quota = "1"
              ExtSubmitInt7Quota = "1"              
              RobotIntDelay      = "1"
              SubmitIntDelay     = "1"
              ExtSubmitInt1Delay = "1"
              ExtSubmitInt2Delay = "1"
              ExtSubmitInt3Delay = "1"
              ExtSubmitInt4Delay = "1"
              ExtSubmitInt5Delay = "1"
              ExtSubmitInt6Delay = "1"
              ExtSubmitInt7Delay = "1"
              ExprIntQuota       = "5"
              ExprIntDelay       = "1"/>
   </Scheduling>
   
   <MultiSubmit Enable="true"/>
   
   <AllowDoubleDollarVar Enable="false"/>

   <Axes ConfigFile="Mada/KRCAxes.xml"/>
   
   <PcFanCheck
      Enable="false"
      ImpulsesPerRevolution="2"
      WarningRevolution="5200"
      AlarmRevolution="4800"/>

   <CabinetFanCheck
      Enable="false"
      ImpulsesPerRevolution="2"
      WarningRevolution="5200"
      AlarmRevolution="4800"/>

   <InfoHandlerThread
      CycleTime="200000"
      PowerOffDelayTime="1000000"/>

   <!-- FctCallChannel
      ; CWrite to $FCT_CALL Channel
      ; Enable=true    - Channel is valid (Task tFct_Call spawned)
      ; Enable=false   - Channel invalid  (Task tFct_Call not spawned)
      ; TaskStackBytes - Task-Stack for tFctCall Task, a minimum of 401408 Bytes has to be allocated.
      ; In case the attribute TaskStackBytes contains a value less than 401408 the siftware will
      ; allocate 401408 Bytes  -->
   <FctCallChannel
      Enable="true" 
      TaskStackBytes="401408"/>
 
  <!-- ************ -->
  <!-- ADS Settings -->
  <!-- ************ -->
  <ADS_TCP_IP>  
    <!-- Data port -->
    <ADS_DATENPORT Value="54100" />
  </ADS_TCP_IP>

  <!-- ***************************************** -->
  <!-- Port Configuration for Cooperating-Robots -->
  <!-- ***************************************** -->
  <CRPORTS>
    <!-- Motion cooperation port -->
    <MOTIONSYNC_PORT Value="5002" />
    <!-- Workspace sharing port -->
    <WORKSPACE_PORT  Value="5003" />
    <!-- Program sync and remote command port -->
    <PROGSYNC_PORT   Value="5004" />
    <!-- Collision Avoidance port -->
    <COLLAVOID_PORT  Value="5020" />
  </CRPORTS>

</KRC>
