=== JuniorNatalin/Selco_Senai/1304915/C/KRC/Roboter/Config/System/Common/Schemes/NGCtrl.xsd
<?xml version="1.0" encoding="UTF-8"?>
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema">
   <xs:include schemaLocation="Version.xsd"/>
   <xs:include schemaLocation="NGCtrlTypes.xsd"/>
   <xs:element name="CtrlParam">
      <xs:complexType>
         <xs:sequence>
            <xs:element ref="Version" minOccurs="0" />
            <xs:element name="Machine" type="machineType"/>
            <xs:element name="Controller" minOccurs="0">
               <xs:complexType>
                  <xs:attribute name="ID" type="xs:unsignedInt" use="required"/>
               </xs:complexType>
            </xs:element>
            <xs:sequence>
               <xs:element name="GlobalParameter" type="GlobalParameterType" minOccurs="0" maxOccurs="unbounded"/>
            </xs:sequence>
            <xs:sequence>
               <xs:element name="Parameter" type="ParameterType" minOccurs="0" maxOccurs="unbounded"/>
            </xs:sequence>
            <xs:element name="DefaultController" type="DefaultControllerType" minOccurs="0">
               <xs:annotation>
                  <xs:documentation>Not supported any more. Kept for backward compatibility. PTP values are used instead.</xs:documentation>
               </xs:annotation>
            </xs:element>
         </xs:sequence>
      </xs:complexType>
   </xs:element>
</xs:schema>

=== JuniorNatalin/Selco_Senai/1304915/C/KRC/Roboter/Config/User/Common/Mada/NGAxis/CtrlA1.xml
<?xml version="1.0" encoding="utf-8"?>
<!--XML file automatically generated by WorkVisual V6.0.15_Build0685.-->
<!--DO NOT EDIT-->
<CtrlParam xsi:noNamespaceSchemaLocation="../../../../System/Common/Schemes/NGCtrl.xsd" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance">
  <Version Label="">
    <Info Version="KUKA V8.7" />
    <Schema Version="1" />
  </Version>
  <Machine Name="#KR16R2010_2 C4" />
  <Controller ID="2" />
  <GlobalParameter Name="CmdPosDelay" Index="0" MinValue="0" MaxValue="0" EvalBoundary="Min" Access="ro" Value="0" />
  <GlobalParameter Name="FFCVelocity" Index="1" MinValue="0" MaxValue="1" EvalBoundary="MinMax" Access="ro" Value="1" />
  <GlobalParameter Name="FFCTorque" Index="2" MinValue="0" MaxValue="1" EvalBoundary="MinMax" Access="ro" Value="1" />
  <GlobalParameter Name="CtrlCycle" Index="3" MinValue="1" MaxValue="0" EvalBoundary="Min" Access="ro" Value="1" />
  <GlobalParameter Name="CtrlOffset" Index="5" MinValue="0" MaxValue="0" EvalBoundary="Min" Access="ro" Value="0" />
  <GlobalParameter Name="Pos2VelFilterFreq" Index="6" MinValue="1" MaxValue="8000" EvalBoundary="MinMax" Access="rw" Value="87.3378" Type="16384" />
  <GlobalParameter Name="MECHPARAM0001" Index="301" MinValue="0" MaxValue="0" EvalBoundary="Off" Access="rwv" Value="0" Type="MLI" />
  <GlobalParameter Name="MECHPARAM0002" Index="9" MinValue="0" MaxValue="0" EvalBoundary="Off" Access="ro" Value="1" />
  <GlobalParameter Name="MECHPARAM0003" Index="10" MinValue="0" MaxValue="0" EvalBoundary="Off" Access="ro" Value="1" />
  <GlobalParameter Name="MECHPARAM0004" Index="11" MinValue="0" MaxValue="0" EvalBoundary="Off" Access="ro" Value="0" />
  <GlobalParameter Name="MECHPARAM0005" Index="12" MinValue="0" MaxValue="0" EvalBoundary="Off" Access="ro" Value="0.75" />
  <GlobalParameter Name="MECHPARAM0006" Index="13" MinValue="0" MaxValue="0" EvalBoundary="Off" Access="ro" Value="1.25" />
  <GlobalParameter Name="MECHPARAM0007" Index="14" MinValue="0" MaxValue="0" EvalBoundary="Off" Access="ro" Value="0.25" />
  <GlobalParameter Name="MECHPARAM0008" Index="15" MinValue="0" MaxValue="0" EvalBoundary="Off" Access="ro" Value="0.6" />
  <GlobalParameter Name="MECHPARAM0009" Index="16" MinValue="0" MaxValue="0" EvalBoundary="Off" Access="ro" Value="1.5" />
  <GlobalParameter Name="MECHPARAM0010" Index="17" MinValue="0" MaxValue="0" EvalBoundary="Off" Access="ro" Value="0.5" />
  <GlobalParameter Name="MECHPARAM0011" Index="100" MinValue="0" MaxValue="0" EvalBoundary="Off" Access="ro" Value="0" />
  <GlobalParameter Name="MECHPARAM0012" Index="101" MinValue="0" MaxValue="0" EvalBoundary="Off" Access="ro" Value="0" />
  <GlobalParameter Name="MECHPARAM0013" Index="102" MinValue="0" MaxValue="0" EvalBoundary="Off" Access="ro" Value="0" />
  <GlobalParameter Name="MECHPARAM0014" Index="103" MinValue="0" MaxValue="0" EvalBoundary="Off" Access="ro" Value="0" />
  <GlobalParameter Name="MECHPARAM0015" Index="104" MinValue="0" MaxValue="0" EvalBoundary="Off" Access="ro" Value="0" />
  <GlobalParameter Name="MECHPARAM0016" Index="105" MinValue="0" MaxValue="0" EvalBoundary="Off" Access="ro" Value="1" />
  <GlobalParameter Name="MECHPARAM0017" Index="106" MinValue="0" MaxValue="0" EvalBoundary="Off" Access="ro" Value="1" />
  <GlobalParameter Name="MECHPARAM0018" Index="107" MinValue="0" MaxValue="0" EvalBoundary="Off" Access="ro" Value="0" />
  <GlobalParameter Name="MECHPARAM0019" Index="108" MinValue="0" MaxValue="0" EvalBoundary="Off" Access="ro" Value="0" />
  <GlobalParameter Name="MECHPARAM0020" Index="109" MinValue="0" MaxValue="0" EvalBoundary="Off" Access="ro" Value="0" />
  <GlobalParameter Name="MECHPARAM0021" Index="110" MinValue="0" MaxValue="0" EvalBoundary="Off" Access="ro" Value="0" />
  <GlobalParameter Name="MECHPARAM0022" Index="111" MinValue="0" MaxValue="0" EvalBoundary="Off" Access="ro" Value="0.01" />
  <GlobalParameter Name="MECHPARAM0023" Index="120" MinValue="0" MaxValue="0" EvalBoundary="Off" Access="ro" Value="0" />
  <GlobalParameter Name="MECHPARAM0024" Index="121" MinValue="0" MaxValue="0" EvalBoundary="Off" Access="ro" Value="0" />
  <GlobalParameter Name="MECHPARAM0025" Index="122" MinValue="0" MaxValue="0" EvalBoundary="Off" Access="ro" Value="0" />
  <GlobalParameter Name="MECHPARAM0026" Index="123" MinValue="0" MaxValue="0" EvalBoundary="Off" Access="ro" Value="0" />
  <GlobalParameter Name="MECHPARAM0027" Index="124" MinValue="0" MaxValue="0" EvalBoundary="Off" Access="ro" Value="0" />
  <GlobalParameter Name="MECHPARAM0028" Index="125" MinValue="0" MaxValue="0" EvalBoundary="Off" Access="ro" Value="0" />
  <GlobalParameter Name="MECHPARAM0029" Index="126" MinValue="0" MaxValue="0" EvalBoundary="Off" Access="ro" Value="0" />
  <GlobalParameter Name="MECHPARAM0030" Index="127" MinValue="0" MaxValue="0" EvalBoundary="Off" Access="ro" Value="0" />
  <GlobalParameter Name="MECHPARAM0031" Index="130" MinValue="0" MaxValue="0" EvalBoundary="Off" Access="ro" Value="0" />
  <GlobalParameter Name="MECHPARAM0032" Index="131" MinValue="0" MaxValue="0" EvalBoundary="Off" Access="ro" Value="0" />
  <GlobalParameter Name="MECHPARAM0033" Index="132" MinValue="0" MaxValue="0" EvalBoundary="Off" Access="ro" Value="0" />
  <GlobalParameter Name="MECHPARAM0034" Index="133" MinValue="0" MaxValue="0" EvalBoundary="Off" Access="ro" Value="0" />
  <GlobalParameter Name="MECHPARAM0035" Index="134" MinValue="0" MaxValue="0" EvalBoundary="Off" Access="ro" Value="0" />
  <GlobalParameter Name="MECHPARAM0036" Index="135" MinValue="0" MaxValue="0" EvalBoundary="Off" Access="ro" Value="0" />
  <GlobalParameter Name="MECHPARAM0037" Index="136" MinValue="0" MaxValue="0" EvalBoundary="Off" Access="ro" Value="0" />
  <GlobalParameter Name="MECHPARAM0038" Index="137" MinValue="0" MaxValue="0" EvalBoundary="Off" Access="ro" Value="0" />
  <GlobalParameter Name="MECHPARAM0039" Index="138" MinValue="0" MaxValue="0" EvalBoundary="Off" Access="ro" Value="0" />
  <GlobalParameter Name="MECHPARAM0040" Index="139" MinValue="0" MaxValue="0" EvalBoundary="Off" Access="ro" Value="0" />
  <GlobalParameter Name="MECHPARAM0041" Index="140" MinValue="0" MaxValue="0" EvalBoundary="Off" Access="ro" Value="0" />
  <GlobalParameter Name="MECHPARAM0042" Index="141" MinValue="0" MaxValue="0" EvalBoundary="Off" Access="ro" Value="0" />
  <GlobalParameter Name="MECHPARAM0043" Index="142" MinValue="0" MaxValue="0" EvalBoundary="Off" Access="ro" Value="0" />
  <GlobalParameter Name="MECHPARAM0059" Index="200" MinValue="0" MaxValue="0" EvalBoundary="Off" Access="ro" Value="300" />
  <GlobalParameter Name="MECHPARAM0069" Index="197" MinValue="0" MaxValue="0" EvalBoundary="Off" Access="ro" Value="0" />
  <GlobalParameter Name="MECHPARAM0070" Index="60" MinValue="0" MaxValue="1" EvalBoundary="Off" Access="rwv" Value="0" Type="MLI" />
  <GlobalParameter Name="MECHPARAM0071" Index="61" MinValue="0" MaxValue="0" EvalBoundary="Off" Access="rwv" Value="999" Type="MLI" />
  <GlobalParameter Name="MECHPARAM0072" Index="62" MinValue="0" MaxValue="0" EvalBoundary="Off" Access="rwv" Value="999" Type="MLI" />
  <GlobalParameter Name="MECHPARAM0073" Index="63" MinValue="0" MaxValue="0" EvalBoundary="Off" Access="rwv" Value="999" Type="MLI" />
  <GlobalParameter Name="MECHPARAM0074" Index="64" MinValue="0" MaxValue="0" EvalBoundary="Off" Access="rwv" Value="999" Type="MLI" />
  <GlobalParameter Name="MECHPARAM0075" Index="65" MinValue="0" MaxValue="0" EvalBoundary="Off" Access="rwv" Value="999" Type="MLI" />
  <GlobalParameter Name="MECHPARAM0076" Index="66" MinValue="0" MaxValue="0" EvalBoundary="Off" Access="rwv" Value="999" Type="MLI" />
  <GlobalParameter Name="MECHPARAM0077" Index="67" MinValue="0" MaxValue="0" EvalBoundary="Off" Access="rwv" Value="999" Type="MLI" />
  <GlobalParameter Name="MECHPARAM0078" Index="68" MinValue="0" MaxValue="0" EvalBoundary="Off" Access="rwv" Value="999" Type="MLI" />
  <GlobalParameter Name="MECHPARAM0079" Index="69" MinValue="0" MaxValue="0" EvalBoundary="Off" Access="rwv" Value="999" Type="MLI" />
  <GlobalParameter Name="MECHPARAM0090" Index="80" MinValue="0" MaxValue="1" EvalBoundary="Off" Access="ro" Value="0" />
  <GlobalParameter Name="MECHPARAM0091" Index="81" MinValue="0" MaxValue="1" EvalBoundary="Off" Access="rwv" Value="0" Type="MLI" />
  <GlobalParameter Name="MECHPARAM0092" Index="82" MinValue="0" MaxValue="1" EvalBoundary="Off" Access="ro" Value="0" />
  <GlobalParameter Name="MECHPARAM0093" Index="83" MinValue="0" MaxValue="1" EvalBoundary="Off" Access="rwv" Value="0" Type="MLI" />
  <GlobalParameter Name="MECHPARAM0094" Index="84" MinValue="0" MaxValue="1" EvalBoundary="Off" Access="ro" Value="0" />
  <GlobalParameter Name="MECHPARAM0095" Index="85" MinValue="0" MaxValue="1" EvalBoundary="Off" Access="ro" Value="0" />
  <GlobalParameter Name="MECHPARAM0096" Index="86" MinValue="0" MaxValue="1" EvalBoundary="Off" Access="ro" Value="0" />
  <GlobalParameter Name="MECHPARAM0097" Index="87" MinValue="0" MaxValue="1" EvalBoundary="Off" Access="rwv" Value="0" Type="MLI" />
  <Parameter Name="PosGain" Index="0" MinValue="0" MaxValue="0" EvalBoundary="Min" Access="rw">
    <Set Name="PTP" Value="13.1" />
    <Set Name="CP" Value="13.1" />
  </Parameter>
  <Parameter Name="PosIntTime" Index="1" MinValue="0" MaxValue="0" EvalBoundary="Min" Access="rw">
    <Set Name="PTP" Value="0" />
    <Set Name="CP" Value="0" />
  </Parameter>
  <Parameter Name="VelGain" Index="2" MinValue="0" MaxValue="0" EvalBoundary="Min" Access="rw">
    <Set Name="PTP" Value="0.019466" />
    <Set Name="CP" Value="0.019466" />
  </Parameter>
  <Parameter Name="VelIntTime" Index="3" MinValue="0" MaxValue="0" EvalBoundary="Min" Access="rw">
    <Set Name="PTP" Value="0.097222" />
    <Set Name="CP" Value="0.097222" />
  </Parameter>
  <Parameter Name="FFCTorque" Index="4" MinValue="0" MaxValue="1" EvalBoundary="MinMax" Access="rw">
    <Set Name="PTP" Value="1" />
    <Set Name="CP" Value="1" />
  </Parameter>
</CtrlParam>
